export const API_CONFIG = {
  mode: import.meta.env.VITE_API_MODE || "live",
  baseURL: import.meta.env.VITE_API_BASE_URL || "/api",
  timeout: Number(import.meta.env.VITE_API_TIMEOUT || 10000),
  sessionTimeoutMs: Number(import.meta.env.VITE_SESSION_TIMEOUT_MS || 1800000),
  endpoints: {
    auth: {
      login: "/auth/login",
      logout: "/auth/logout",
      refresh: "/auth/refresh",
      profile: "/auth/profile",
      sessions: "/auth/sessions",
      policies: "/auth/policies",
    },
    dashboard: "/operations/overview",
    operations: {
      events: "/operations/events",
      timeline: "/operations/timeline",
      changes: "/operations/changes",
    },
    masterControl: {
      status: "/broadcast/master-control/status",
      takeover: "/broadcast/master-control/takeover",
    },
    media: {
      ingestQueue: "/infrastructure/ffmpeg/jobs",
      library: "/media/library/assets",
    },
    scheduler: "/broadcast/playout/schedule",
    streaming: {
      health: "/streaming/endpoints/health",
      failover: "/streaming/endpoints/failover",
      obs: "/streaming/obs/connections",
      ffmpeg: "/streaming/ffmpeg/jobs",
      rtmp: "/streaming/rtmp/endpoints",
      hls: "/streaming/hls/endpoints",
      livekit: "/streaming/livekit/rooms",
      alerts: "/streaming/alerts",
      logs: "/streaming/logs",
      refresh: "/streaming/endpoints/refresh",
    },
    infrastructure: {
      overview: "/infrastructure/noc/overview",
      containers: "/infrastructure/containers/status",
      containersStart: "/infrastructure/containers/start",
      containersStop: "/infrastructure/containers/stop",
      containersRestart: "/infrastructure/containers/restart",
      containersLogs: "/infrastructure/containers/logs",
      containersAlerts: "/infrastructure/containers/alerts",
      monitoring: "/infrastructure/monitoring/checks",
      monitoringPause: "/infrastructure/monitoring/pause",
      monitoringResume: "/infrastructure/monitoring/resume",
      monitoringRefresh: "/infrastructure/monitoring/refresh",
      monitoringIncidents: "/infrastructure/monitoring/incidents",
      monitoringLogs: "/infrastructure/monitoring/logs",
      monitoringAcknowledge: "/infrastructure/monitoring/acknowledge",
      proxy: "/infrastructure/proxy/routes",
      proxyHosts: "/infrastructure/proxy/hosts",
      proxyHostToggle: "/infrastructure/proxy/hosts/toggle",
      proxyCertificates: "/infrastructure/proxy/certificates",
      proxyLogs: "/infrastructure/proxy/logs",
      proxyAlerts: "/infrastructure/proxy/alerts",
      proxyRenewCertificate: "/infrastructure/proxy/certificates/renew",
      proxyReload: "/infrastructure/proxy/reload",
      proxmoxVms: "/infrastructure/proxmox/vms",
      proxmoxNodes: "/infrastructure/proxmox/nodes",
      proxmoxStorage: "/infrastructure/proxmox/storage",
      proxmoxTasks: "/infrastructure/proxmox/tasks",
      proxmoxCluster: "/infrastructure/proxmox/cluster",
      proxmoxVmStart: "/infrastructure/proxmox/vms/start",
      proxmoxVmStop: "/infrastructure/proxmox/vms/stop",
      proxmoxLogs: "/infrastructure/proxmox/logs",
      proxmoxAlerts: "/infrastructure/proxmox/alerts",
      proxmoxRebootVm: "/infrastructure/proxmox/vms/reboot",
      proxmoxConsole: "/infrastructure/proxmox/vms/console",
      ubuntuServers: "/infrastructure/ubuntu/servers",
      storageVolumes: "/infrastructure/storage/volumes",
      networkLinks: "/infrastructure/network/links",
    },
    ai: {
      incidents: "/ai/operations/incidents",
      recommendations: "/ai/operations/recommendations",
    },
    users: "/iam/users",
    audit: "/iam/audit/logs",
    settings: "/administration/settings",

    // Backward-compatible aliases for current mock mode and staged migration.
    channels: "/broadcast/master-control/status",
    mediaLegacy: "/media",
    streamingLegacy: "/streaming",
    analytics: "/infrastructure/monitoring/checks",
  },
};

export const ENVIRONMENT = import.meta.env.MODE || "development";
export const IS_PRODUCTION = ENVIRONMENT === "production";
