export const PERMISSIONS = Object.freeze({
  ALL: "*",
  SYSTEM_AUTHENTICATED: "system.authenticated",
  AUTH_PROFILE_READ: "auth.profile.read",
  AUTH_SESSIONS_READ: "auth.sessions.read",
  AUTH_POLICIES_READ: "auth.policies.read",
  AUTH_LOGOUT: "auth.logout",
  CONNECTIVITY_READ: "connectivity.read",
  PROVIDER_CAPABILITIES_READ: "providers.capabilities.read",
  INFRA_PROXMOX_READ: "infrastructure.proxmox.read",
  INFRA_PROXMOX_ACTION: "infrastructure.proxmox.action",
  INFRA_CONTAINERS_READ: "infrastructure.containers.read",
  INFRA_CONTAINERS_ACTION: "infrastructure.containers.action",
  INFRA_MONITORING_READ: "infrastructure.monitoring.read",
  INFRA_MONITORING_ACTION: "infrastructure.monitoring.action",
  INFRA_PROXY_READ: "infrastructure.proxy.read",
  INFRA_PROXY_ACTION: "infrastructure.proxy.action",
  PROVIDER_STATE_READ: "providers.state.read",
  OPERATIONS_EVENTS_READ: "operations.events.read",
  OPERATIONS_OVERVIEW_READ: "operations.overview.read",
  OPERATIONS_HEALTH_READ: "operations.health.read",
  OPERATIONS_TIMELINE_READ: "operations.timeline.read",
  OPERATIONS_CHANGES_READ: "operations.changes.read",
  IAM_AUDIT_READ: "iam.audit.read",
  IAM_USERS_READ: "iam.users.read",
  ADMIN_SETTINGS_READ: "administration.settings.read",
  STREAMING_READ: "streaming.read",
  STREAMING_ACTION: "streaming.action",
  BROADCAST_READ: "broadcast.read",
  BROADCAST_ACTION: "broadcast.action",
  MEDIA_LIBRARY_READ: "media.library.read",
  AI_OPERATIONS_READ: "ai.operations.read",
  INFRA_NOC_READ: "infrastructure.noc.read",
  INFRA_UBUNTU_READ: "infrastructure.ubuntu.read",
  INFRA_STORAGE_READ: "infrastructure.storage.read",
  INFRA_NETWORK_READ: "infrastructure.network.read",
  INFRA_FFMPEG_READ: "infrastructure.ffmpeg.read",
  REPORTERS_READ: "reporters.read",
  REPORTERS_WRITE: "reporters.write",
  STUDIOS_READ: "studios.read",
  STUDIOS_WRITE: "studios.write",
  ASSIGNMENTS_READ: "assignments.read",
  ASSIGNMENTS_WRITE: "assignments.write",
  PRESENCE_READ: "presence.read",
  PRESENCE_UPDATE: "presence.update",
  PRESENCE_OVERRIDE: "presence.override",
  MEDIA_CAPABILITIES_READ: "media.capabilities.read",
  MEDIA_ROOMS_READ: "media.rooms.read",
  MEDIA_ROOMS_WRITE: "media.rooms.write",
  MEDIA_SESSION_JOIN: "media.session.join",
  MEDIA_SESSION_LEAVE: "media.session.leave",
  MEDIA_DEVICE_SELECT: "media.device.select",
  MEDIA_PUBLISHER_CONTROL: "media.publisher.control",
  MEDIA_PRODUCER_CONTROL: "media.producer.control",
  MEDIA_SESSION_READ: "media.session.read",
  MEDIA_SESSION_CREATE: "media.session.create",
  MEDIA_SESSION_UPDATE: "media.session.update",
  MEDIA_SESSION_CLOSE: "media.session.close",
  MEDIA_PARTICIPANT_MANAGE: "media.participant.manage",
  MEDIA_PRODUCER_TRANSFER: "media.producer.transfer",
  MEDIA_SESSION_READINESS_READ: "media.session.readiness.read",
  MEDIA_SESSION_READINESS_WRITE: "media.session.readiness.write",
  MEDIA_SESSION_LIVE_CONTROL: "media.session.live.control",
});

export const PERMISSION_CATALOG = Object.freeze([
  { key: PERMISSIONS.ALL, description: "All permissions" },
  { key: PERMISSIONS.SYSTEM_AUTHENTICATED, description: "Authenticated TMOS API access" },
  { key: PERMISSIONS.AUTH_PROFILE_READ, description: "Read current user profile" },
  { key: PERMISSIONS.AUTH_SESSIONS_READ, description: "Read active and historical sessions" },
  { key: PERMISSIONS.AUTH_POLICIES_READ, description: "Read active authorization policies" },
  { key: PERMISSIONS.AUTH_LOGOUT, description: "Terminate the current authenticated session" },
  { key: PERMISSIONS.CONNECTIVITY_READ, description: "Read VPN readiness and connectivity state" },
  { key: PERMISSIONS.PROVIDER_CAPABILITIES_READ, description: "Read provider capability catalog" },
  { key: PERMISSIONS.INFRA_PROXMOX_READ, description: "Read Proxmox infrastructure data" },
  { key: PERMISSIONS.INFRA_PROXMOX_ACTION, description: "Execute Proxmox VM actions" },
  { key: PERMISSIONS.INFRA_CONTAINERS_READ, description: "Read container infrastructure data" },
  { key: PERMISSIONS.INFRA_CONTAINERS_ACTION, description: "Execute container control actions" },
  { key: PERMISSIONS.INFRA_MONITORING_READ, description: "Read monitoring checks and incidents" },
  { key: PERMISSIONS.INFRA_MONITORING_ACTION, description: "Execute monitoring control actions" },
  { key: PERMISSIONS.INFRA_PROXY_READ, description: "Read proxy infrastructure data" },
  { key: PERMISSIONS.INFRA_PROXY_ACTION, description: "Execute proxy control actions" },
  { key: PERMISSIONS.PROVIDER_STATE_READ, description: "Read persisted provider state" },
  { key: PERMISSIONS.OPERATIONS_EVENTS_READ, description: "Read operations event stream" },
  { key: PERMISSIONS.OPERATIONS_OVERVIEW_READ, description: "Read operations overview" },
  { key: PERMISSIONS.OPERATIONS_HEALTH_READ, description: "Read operations system health summary" },
  { key: PERMISSIONS.OPERATIONS_TIMELINE_READ, description: "Read operations timeline" },
  { key: PERMISSIONS.OPERATIONS_CHANGES_READ, description: "Read operations changes" },
  { key: PERMISSIONS.IAM_AUDIT_READ, description: "Read IAM audit logs" },
  { key: PERMISSIONS.IAM_USERS_READ, description: "Read IAM user resources" },
  { key: PERMISSIONS.ADMIN_SETTINGS_READ, description: "Read administration settings" },
  { key: PERMISSIONS.STREAMING_READ, description: "Read streaming infrastructure data" },
  { key: PERMISSIONS.STREAMING_ACTION, description: "Execute streaming control actions" },
  { key: PERMISSIONS.BROADCAST_READ, description: "Read broadcast control resources" },
  { key: PERMISSIONS.BROADCAST_ACTION, description: "Execute broadcast control actions" },
  { key: PERMISSIONS.MEDIA_LIBRARY_READ, description: "Read media library resources" },
  { key: PERMISSIONS.AI_OPERATIONS_READ, description: "Read AI operations resources" },
  { key: PERMISSIONS.INFRA_NOC_READ, description: "Read NOC infrastructure resources" },
  { key: PERMISSIONS.INFRA_UBUNTU_READ, description: "Read Ubuntu infrastructure resources" },
  { key: PERMISSIONS.INFRA_STORAGE_READ, description: "Read storage infrastructure resources" },
  { key: PERMISSIONS.INFRA_NETWORK_READ, description: "Read network infrastructure resources" },
  { key: PERMISSIONS.INFRA_FFMPEG_READ, description: "Read FFmpeg infrastructure resources" },
  { key: PERMISSIONS.REPORTERS_READ, description: "Read reporter records" },
  { key: PERMISSIONS.REPORTERS_WRITE, description: "Create, update, and delete reporter records" },
  { key: PERMISSIONS.STUDIOS_READ, description: "Read studio records" },
  { key: PERMISSIONS.STUDIOS_WRITE, description: "Create, update, and delete studio records" },
  { key: PERMISSIONS.ASSIGNMENTS_READ, description: "Read assignment records" },
  { key: PERMISSIONS.ASSIGNMENTS_WRITE, description: "Create, update, and delete assignment records" },
  { key: PERMISSIONS.PRESENCE_READ, description: "Read realtime reporter presence status" },
  { key: PERMISSIONS.PRESENCE_UPDATE, description: "Update reporter presence status and heartbeat" },
  { key: PERMISSIONS.PRESENCE_OVERRIDE, description: "Override reporter presence state as producer/control room" },
  { key: PERMISSIONS.MEDIA_CAPABILITIES_READ, description: "Read media provider capabilities" },
  { key: PERMISSIONS.MEDIA_ROOMS_READ, description: "Read media room and participant state" },
  { key: PERMISSIONS.MEDIA_ROOMS_WRITE, description: "Create and manage media rooms" },
  { key: PERMISSIONS.MEDIA_SESSION_JOIN, description: "Join media sessions" },
  { key: PERMISSIONS.MEDIA_SESSION_LEAVE, description: "Leave media sessions" },
  { key: PERMISSIONS.MEDIA_DEVICE_SELECT, description: "Update participant device selection" },
  { key: PERMISSIONS.MEDIA_PUBLISHER_CONTROL, description: "Toggle participant publisher state" },
  { key: PERMISSIONS.MEDIA_PRODUCER_CONTROL, description: "Apply producer control actions to participants" },
  { key: PERMISSIONS.MEDIA_SESSION_READ, description: "Read orchestrated media session metadata" },
  { key: PERMISSIONS.MEDIA_SESSION_CREATE, description: "Create orchestrated media sessions" },
  { key: PERMISSIONS.MEDIA_SESSION_UPDATE, description: "Update orchestrated media session metadata" },
  { key: PERMISSIONS.MEDIA_SESSION_CLOSE, description: "Close media sessions" },
  { key: PERMISSIONS.MEDIA_PARTICIPANT_MANAGE, description: "Invite/remove participants and operate participant lifecycle" },
  { key: PERMISSIONS.MEDIA_PRODUCER_TRANSFER, description: "Transfer producer ownership within a media session" },
  { key: PERMISSIONS.MEDIA_SESSION_READINESS_READ, description: "Read session readiness status and blockers" },
  { key: PERMISSIONS.MEDIA_SESSION_READINESS_WRITE, description: "Report participant session readiness" },
  { key: PERMISSIONS.MEDIA_SESSION_LIVE_CONTROL, description: "Control session live and stop-live workflows" },
]);

export const ROLE_CATALOG = Object.freeze([
  { key: "Administrator", description: "Full TMOS administrative access" },
  { key: "Operator", description: "Operational control with limited administrative scope" },
  { key: "Producer", description: "Broadcast producer control room access" },
  { key: "Viewer", description: "Read-only observability and monitoring access" },
]);

export const ROLE_PERMISSION_CATALOG = Object.freeze({
  Administrator: [PERMISSIONS.ALL],
  Operator: [
    PERMISSIONS.SYSTEM_AUTHENTICATED,
    PERMISSIONS.AUTH_PROFILE_READ,
    PERMISSIONS.AUTH_SESSIONS_READ,
    PERMISSIONS.AUTH_POLICIES_READ,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.CONNECTIVITY_READ,
    PERMISSIONS.PROVIDER_CAPABILITIES_READ,
    PERMISSIONS.INFRA_PROXMOX_READ,
    PERMISSIONS.INFRA_PROXMOX_ACTION,
    PERMISSIONS.INFRA_CONTAINERS_READ,
    PERMISSIONS.INFRA_CONTAINERS_ACTION,
    PERMISSIONS.INFRA_MONITORING_READ,
    PERMISSIONS.INFRA_MONITORING_ACTION,
    PERMISSIONS.INFRA_PROXY_READ,
    PERMISSIONS.INFRA_PROXY_ACTION,
    PERMISSIONS.PROVIDER_STATE_READ,
    PERMISSIONS.OPERATIONS_EVENTS_READ,
    PERMISSIONS.OPERATIONS_OVERVIEW_READ,
    PERMISSIONS.OPERATIONS_HEALTH_READ,
    PERMISSIONS.OPERATIONS_TIMELINE_READ,
    PERMISSIONS.OPERATIONS_CHANGES_READ,
    PERMISSIONS.IAM_AUDIT_READ,
    PERMISSIONS.STREAMING_READ,
    PERMISSIONS.STREAMING_ACTION,
    PERMISSIONS.BROADCAST_READ,
    PERMISSIONS.BROADCAST_ACTION,
    PERMISSIONS.MEDIA_LIBRARY_READ,
    PERMISSIONS.AI_OPERATIONS_READ,
    PERMISSIONS.INFRA_NOC_READ,
    PERMISSIONS.INFRA_UBUNTU_READ,
    PERMISSIONS.INFRA_STORAGE_READ,
    PERMISSIONS.INFRA_NETWORK_READ,
    PERMISSIONS.INFRA_FFMPEG_READ,
    PERMISSIONS.REPORTERS_READ,
    PERMISSIONS.REPORTERS_WRITE,
    PERMISSIONS.STUDIOS_READ,
    PERMISSIONS.STUDIOS_WRITE,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.ASSIGNMENTS_WRITE,
    PERMISSIONS.PRESENCE_READ,
    PERMISSIONS.PRESENCE_UPDATE,
    PERMISSIONS.PRESENCE_OVERRIDE,
    PERMISSIONS.MEDIA_CAPABILITIES_READ,
    PERMISSIONS.MEDIA_ROOMS_READ,
    PERMISSIONS.MEDIA_ROOMS_WRITE,
    PERMISSIONS.MEDIA_SESSION_JOIN,
    PERMISSIONS.MEDIA_SESSION_LEAVE,
    PERMISSIONS.MEDIA_DEVICE_SELECT,
    PERMISSIONS.MEDIA_PUBLISHER_CONTROL,
    PERMISSIONS.MEDIA_PRODUCER_CONTROL,
    PERMISSIONS.MEDIA_SESSION_READ,
    PERMISSIONS.MEDIA_SESSION_CREATE,
    PERMISSIONS.MEDIA_SESSION_UPDATE,
    PERMISSIONS.MEDIA_SESSION_CLOSE,
    PERMISSIONS.MEDIA_PARTICIPANT_MANAGE,
    PERMISSIONS.MEDIA_PRODUCER_TRANSFER,
    PERMISSIONS.MEDIA_SESSION_READINESS_READ,
    PERMISSIONS.MEDIA_SESSION_READINESS_WRITE,
    PERMISSIONS.MEDIA_SESSION_LIVE_CONTROL,
  ],
  Producer: [
    PERMISSIONS.SYSTEM_AUTHENTICATED,
    PERMISSIONS.AUTH_PROFILE_READ,
    PERMISSIONS.AUTH_POLICIES_READ,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.REPORTERS_READ,
    PERMISSIONS.REPORTERS_WRITE,
    PERMISSIONS.STUDIOS_READ,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.PRESENCE_READ,
    PERMISSIONS.PRESENCE_OVERRIDE,
    PERMISSIONS.MEDIA_CAPABILITIES_READ,
    PERMISSIONS.MEDIA_ROOMS_READ,
    PERMISSIONS.MEDIA_SESSION_JOIN,
    PERMISSIONS.MEDIA_SESSION_LEAVE,
    PERMISSIONS.MEDIA_DEVICE_SELECT,
    PERMISSIONS.MEDIA_PRODUCER_CONTROL,
    PERMISSIONS.MEDIA_SESSION_READ,
    PERMISSIONS.MEDIA_SESSION_CREATE,
    PERMISSIONS.MEDIA_SESSION_UPDATE,
    PERMISSIONS.MEDIA_SESSION_CLOSE,
    PERMISSIONS.MEDIA_PARTICIPANT_MANAGE,
    PERMISSIONS.MEDIA_PRODUCER_TRANSFER,
    PERMISSIONS.MEDIA_SESSION_READINESS_READ,
    PERMISSIONS.MEDIA_SESSION_READINESS_WRITE,
    PERMISSIONS.MEDIA_SESSION_LIVE_CONTROL,
  ],
  Viewer: [
    PERMISSIONS.SYSTEM_AUTHENTICATED,
    PERMISSIONS.AUTH_PROFILE_READ,
    PERMISSIONS.AUTH_POLICIES_READ,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.CONNECTIVITY_READ,
    PERMISSIONS.PROVIDER_CAPABILITIES_READ,
    PERMISSIONS.INFRA_PROXMOX_READ,
    PERMISSIONS.INFRA_CONTAINERS_READ,
    PERMISSIONS.INFRA_MONITORING_READ,
    PERMISSIONS.INFRA_PROXY_READ,
    PERMISSIONS.PROVIDER_STATE_READ,
    PERMISSIONS.OPERATIONS_EVENTS_READ,
    PERMISSIONS.OPERATIONS_OVERVIEW_READ,
    PERMISSIONS.OPERATIONS_HEALTH_READ,
    PERMISSIONS.OPERATIONS_TIMELINE_READ,
    PERMISSIONS.OPERATIONS_CHANGES_READ,
    PERMISSIONS.IAM_AUDIT_READ,
    PERMISSIONS.STREAMING_READ,
    PERMISSIONS.BROADCAST_READ,
    PERMISSIONS.MEDIA_LIBRARY_READ,
    PERMISSIONS.AI_OPERATIONS_READ,
    PERMISSIONS.INFRA_NOC_READ,
    PERMISSIONS.INFRA_UBUNTU_READ,
    PERMISSIONS.INFRA_STORAGE_READ,
    PERMISSIONS.INFRA_NETWORK_READ,
    PERMISSIONS.INFRA_FFMPEG_READ,
    PERMISSIONS.REPORTERS_READ,
    PERMISSIONS.STUDIOS_READ,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.PRESENCE_READ,
    PERMISSIONS.MEDIA_CAPABILITIES_READ,
    PERMISSIONS.MEDIA_ROOMS_READ,
    PERMISSIONS.MEDIA_SESSION_READ,
    PERMISSIONS.MEDIA_SESSION_READINESS_READ,
  ],
});
