export const PERMISSIONS = Object.freeze({
  ALL: "*",
  SYSTEM_AUTHENTICATED: "system.authenticated",
  AUTH_PROFILE_READ: "auth.profile.read",
  AUTH_SESSIONS_READ: "auth.sessions.read",
  AUTH_POLICIES_READ: "auth.policies.read",
  AUTH_LOGOUT: "auth.logout",
  CONNECTIVITY_READ: "connectivity.read",
  PROVIDER_CAPABILITIES_READ: "providers.capabilities.read",
  INFRA_PROXMOX_READ: "infrastructure.proxmox.read",
  INFRA_PROXMOX_ACTION: "infrastructure.proxmox.action",
  INFRA_CONTAINERS_READ: "infrastructure.containers.read",
  INFRA_CONTAINERS_ACTION: "infrastructure.containers.action",
  INFRA_MONITORING_READ: "infrastructure.monitoring.read",
  INFRA_MONITORING_ACTION: "infrastructure.monitoring.action",
  INFRA_PROXY_READ: "infrastructure.proxy.read",
  INFRA_PROXY_ACTION: "infrastructure.proxy.action",
  PROVIDER_STATE_READ: "providers.state.read",
  OPERATIONS_EVENTS_READ: "operations.events.read",
  OPERATIONS_OVERVIEW_READ: "operations.overview.read",
  OPERATIONS_TIMELINE_READ: "operations.timeline.read",
  OPERATIONS_CHANGES_READ: "operations.changes.read",
  IAM_AUDIT_READ: "iam.audit.read",
  IAM_USERS_READ: "iam.users.read",
  ADMIN_SETTINGS_READ: "administration.settings.read",
  STREAMING_READ: "streaming.read",
  STREAMING_ACTION: "streaming.action",
  BROADCAST_READ: "broadcast.read",
  BROADCAST_ACTION: "broadcast.action",
  MEDIA_LIBRARY_READ: "media.library.read",
  AI_OPERATIONS_READ: "ai.operations.read",
  INFRA_NOC_READ: "infrastructure.noc.read",
  INFRA_UBUNTU_READ: "infrastructure.ubuntu.read",
  INFRA_STORAGE_READ: "infrastructure.storage.read",
  INFRA_NETWORK_READ: "infrastructure.network.read",
  INFRA_FFMPEG_READ: "infrastructure.ffmpeg.read",
});

export const PERMISSION_CATALOG = Object.freeze([
  { key: PERMISSIONS.ALL, description: "All permissions" },
  { key: PERMISSIONS.SYSTEM_AUTHENTICATED, description: "Authenticated TMOS API access" },
  { key: PERMISSIONS.AUTH_PROFILE_READ, description: "Read current user profile" },
  { key: PERMISSIONS.AUTH_SESSIONS_READ, description: "Read active and historical sessions" },
  { key: PERMISSIONS.AUTH_POLICIES_READ, description: "Read active authorization policies" },
  { key: PERMISSIONS.AUTH_LOGOUT, description: "Terminate the current authenticated session" },
  { key: PERMISSIONS.CONNECTIVITY_READ, description: "Read VPN readiness and connectivity state" },
  { key: PERMISSIONS.PROVIDER_CAPABILITIES_READ, description: "Read provider capability catalog" },
  { key: PERMISSIONS.INFRA_PROXMOX_READ, description: "Read Proxmox infrastructure data" },
  { key: PERMISSIONS.INFRA_PROXMOX_ACTION, description: "Execute Proxmox VM actions" },
  { key: PERMISSIONS.INFRA_CONTAINERS_READ, description: "Read container infrastructure data" },
  { key: PERMISSIONS.INFRA_CONTAINERS_ACTION, description: "Execute container control actions" },
  { key: PERMISSIONS.INFRA_MONITORING_READ, description: "Read monitoring checks and incidents" },
  { key: PERMISSIONS.INFRA_MONITORING_ACTION, description: "Execute monitoring control actions" },
  { key: PERMISSIONS.INFRA_PROXY_READ, description: "Read proxy infrastructure data" },
  { key: PERMISSIONS.INFRA_PROXY_ACTION, description: "Execute proxy control actions" },
  { key: PERMISSIONS.PROVIDER_STATE_READ, description: "Read persisted provider state" },
  { key: PERMISSIONS.OPERATIONS_EVENTS_READ, description: "Read operations event stream" },
  { key: PERMISSIONS.OPERATIONS_OVERVIEW_READ, description: "Read operations overview" },
  { key: PERMISSIONS.OPERATIONS_TIMELINE_READ, description: "Read operations timeline" },
  { key: PERMISSIONS.OPERATIONS_CHANGES_READ, description: "Read operations changes" },
  { key: PERMISSIONS.IAM_AUDIT_READ, description: "Read IAM audit logs" },
  { key: PERMISSIONS.IAM_USERS_READ, description: "Read IAM user resources" },
  { key: PERMISSIONS.ADMIN_SETTINGS_READ, description: "Read administration settings" },
  { key: PERMISSIONS.STREAMING_READ, description: "Read streaming infrastructure data" },
  { key: PERMISSIONS.STREAMING_ACTION, description: "Execute streaming control actions" },
  { key: PERMISSIONS.BROADCAST_READ, description: "Read broadcast control resources" },
  { key: PERMISSIONS.BROADCAST_ACTION, description: "Execute broadcast control actions" },
  { key: PERMISSIONS.MEDIA_LIBRARY_READ, description: "Read media library resources" },
  { key: PERMISSIONS.AI_OPERATIONS_READ, description: "Read AI operations resources" },
  { key: PERMISSIONS.INFRA_NOC_READ, description: "Read NOC infrastructure resources" },
  { key: PERMISSIONS.INFRA_UBUNTU_READ, description: "Read Ubuntu infrastructure resources" },
  { key: PERMISSIONS.INFRA_STORAGE_READ, description: "Read storage infrastructure resources" },
  { key: PERMISSIONS.INFRA_NETWORK_READ, description: "Read network infrastructure resources" },
  { key: PERMISSIONS.INFRA_FFMPEG_READ, description: "Read FFmpeg infrastructure resources" },
]);

export const ROLE_CATALOG = Object.freeze([
  { key: "Administrator", description: "Full TMOS administrative access" },
  { key: "Operator", description: "Operational control with limited administrative scope" },
  { key: "Viewer", description: "Read-only observability and monitoring access" },
]);

export const ROLE_PERMISSION_CATALOG = Object.freeze({
  Administrator: [PERMISSIONS.ALL],
  Operator: [
    PERMISSIONS.SYSTEM_AUTHENTICATED,
    PERMISSIONS.AUTH_PROFILE_READ,
    PERMISSIONS.AUTH_SESSIONS_READ,
    PERMISSIONS.AUTH_POLICIES_READ,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.CONNECTIVITY_READ,
    PERMISSIONS.PROVIDER_CAPABILITIES_READ,
    PERMISSIONS.INFRA_PROXMOX_READ,
    PERMISSIONS.INFRA_PROXMOX_ACTION,
    PERMISSIONS.INFRA_CONTAINERS_READ,
    PERMISSIONS.INFRA_CONTAINERS_ACTION,
    PERMISSIONS.INFRA_MONITORING_READ,
    PERMISSIONS.INFRA_MONITORING_ACTION,
    PERMISSIONS.INFRA_PROXY_READ,
    PERMISSIONS.INFRA_PROXY_ACTION,
    PERMISSIONS.PROVIDER_STATE_READ,
    PERMISSIONS.OPERATIONS_EVENTS_READ,
    PERMISSIONS.OPERATIONS_OVERVIEW_READ,
    PERMISSIONS.OPERATIONS_TIMELINE_READ,
    PERMISSIONS.OPERATIONS_CHANGES_READ,
    PERMISSIONS.IAM_AUDIT_READ,
    PERMISSIONS.STREAMING_READ,
    PERMISSIONS.STREAMING_ACTION,
    PERMISSIONS.BROADCAST_READ,
    PERMISSIONS.BROADCAST_ACTION,
    PERMISSIONS.MEDIA_LIBRARY_READ,
    PERMISSIONS.AI_OPERATIONS_READ,
    PERMISSIONS.INFRA_NOC_READ,
    PERMISSIONS.INFRA_UBUNTU_READ,
    PERMISSIONS.INFRA_STORAGE_READ,
    PERMISSIONS.INFRA_NETWORK_READ,
    PERMISSIONS.INFRA_FFMPEG_READ,
  ],
  Viewer: [
    PERMISSIONS.SYSTEM_AUTHENTICATED,
    PERMISSIONS.AUTH_PROFILE_READ,
    PERMISSIONS.AUTH_POLICIES_READ,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.CONNECTIVITY_READ,
    PERMISSIONS.PROVIDER_CAPABILITIES_READ,
    PERMISSIONS.INFRA_PROXMOX_READ,
    PERMISSIONS.INFRA_CONTAINERS_READ,
    PERMISSIONS.INFRA_MONITORING_READ,
    PERMISSIONS.INFRA_PROXY_READ,
    PERMISSIONS.PROVIDER_STATE_READ,
    PERMISSIONS.OPERATIONS_EVENTS_READ,
    PERMISSIONS.OPERATIONS_OVERVIEW_READ,
    PERMISSIONS.OPERATIONS_TIMELINE_READ,
    PERMISSIONS.OPERATIONS_CHANGES_READ,
    PERMISSIONS.IAM_AUDIT_READ,
    PERMISSIONS.STREAMING_READ,
    PERMISSIONS.BROADCAST_READ,
    PERMISSIONS.MEDIA_LIBRARY_READ,
    PERMISSIONS.AI_OPERATIONS_READ,
    PERMISSIONS.INFRA_NOC_READ,
    PERMISSIONS.INFRA_UBUNTU_READ,
    PERMISSIONS.INFRA_STORAGE_READ,
    PERMISSIONS.INFRA_NETWORK_READ,
    PERMISSIONS.INFRA_FFMPEG_READ,
  ],
});
